package com.tsystems.javaschool.vm.client.panels.customer;

import com.toedter.calendar.JCalendar;
import com.tsystems.javaschool.vm.client.Communicator;
import com.tsystems.javaschool.vm.dto.TicketDTO;
import com.tsystems.javaschool.vm.exception.InvalidIdException;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Calendar;
import java.util.Locale;

public class PassengerPanel extends JPanel {

    private JFrame parent;
    private Long departureBoardId;
    private Long arriveBoardId;
    /**
     * Creates new form PassengerPanel
     */
    public PassengerPanel(JFrame parent, Long departureBoardId, Long arriveBoardId) {
        this.parent = parent;
        this.departureBoardId = departureBoardId;
        this.arriveBoardId = arriveBoardId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        firstNameLabel = new JLabel("First Name");
        firstNameField = new JTextField();
        lastNameField = new JTextField();
        lastNameLabel = new JLabel("Last Name");
        calendar = new JCalendar();
        okButton = new JButton("OK");
        birthDateLabel = new JLabel("Date of birth");
        cancelButton = new JButton("Cancel");
        jLabel1 = new JLabel("Please enter Your first name and last name in the appropriate fields and choose Your");
        jLabel2 = new JLabel("date of birth in the calendar on the right of the frame. Then click button \"OK\".");
        jLabel3 = new JLabel("Please note that you can buy tickets at least 10 minutes before the departure of the train");

        calendar.setLocale(Locale.ENGLISH);

        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                Calendar birthDate = calendar.getCalendar();
                birthDate.set(Calendar.HOUR_OF_DAY, 0);
                birthDate.set(Calendar.MINUTE, 0);
                birthDate.set(Calendar.SECOND, 0);
                birthDate.set(Calendar.MILLISECOND, 0);
                String firstName = firstNameField.getText();
                String lastName = lastNameField.getText();
                if (firstName != null && !firstName.equals("") && lastName != null ) {
                    try {
                        TicketDTO ticketDTO = Communicator.buyTicketAction(firstName, lastName, birthDate, departureBoardId, arriveBoardId);
                        JOptionPane.showMessageDialog(parent, "Ticket is successfully bought id = " + ticketDTO.getTicketId());
                        parent.dispose();
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(parent, "Connection failed: " + e.getClass() + " " + e.getMessage());
                        parent.dispose();
                    } catch (InvalidIdException e) {
                        JOptionPane.showMessageDialog(parent, "Board Id's " + departureBoardId +
                                " or " + arriveBoardId + " don't exist");
                        parent.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(parent, "Error: " + e.getMessage() );
                    }
                } else {
                    JOptionPane.showMessageDialog(parent, "Fill at least your first name! (You can leave the field Last Name empty only if you don't have it)");
                }

                parent.dispose();

            }
        });

        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parent.dispose();
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(firstNameLabel, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(24, 24, 24)
                                                                .addComponent(firstNameField, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(lastNameLabel)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(lastNameField, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(birthDateLabel)
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(okButton, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(13, 13, 13))
                                                        .addComponent(calendar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(26, 26, 26)
                                .addComponent(birthDateLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(calendar, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(okButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(firstNameLabel)
                                                        .addComponent(firstNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lastNameLabel)
                                                        .addComponent(lastNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private JLabel birthDateLabel;
    private JCalendar calendar;
    private JButton cancelButton;
    private JTextField firstNameField;
    private JLabel firstNameLabel;
    private JTextField lastNameField;
    private JLabel lastNameLabel;
    private JButton okButton;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;

    // End of variables declaration
}