package com.tsystems.javaschool.vm.client.panels.customer;

import com.toedter.calendar.JCalendar;
import com.tsystems.javaschool.vm.client.Communicator;
import com.tsystems.javaschool.vm.domain.Board;
import com.tsystems.javaschool.vm.dto.PassengerDTO;
import com.tsystems.javaschool.vm.dto.TicketDTO;
import com.tsystems.javaschool.vm.exception.InvalidIdException;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;

public class PassengerPanel extends javax.swing.JPanel {

    private JFrame parent;
    private Long departureBoardId;
    private Long arriveBoardId;
    /**
     * Creates new form PassengerPanel
     */
    public PassengerPanel(JFrame parent, Long departureBoardId, Long arriveBoardId) {
        this.parent = parent;
        this.departureBoardId = departureBoardId;
        this.arriveBoardId = arriveBoardId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        calendar = new JCalendar();
        okButton = new javax.swing.JButton();
        birthDateLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        firstNameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");



        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calendar birthDate = calendar.getCalendar();
                birthDate.set(Calendar.HOUR, 0);
                birthDate.set(Calendar.MINUTE, 0);
                birthDate.set(Calendar.SECOND, 0);
                birthDate.set(Calendar.MILLISECOND, 0);
                String firstName = firstNameField.getText();
                String lastName = lastNameField.getText();
                if (firstName != null && !firstName.equals("") && lastName != null ) {
                    try {
                        TicketDTO ticketDTO = Communicator.buyTicketAction(firstName, lastName, birthDate, departureBoardId, arriveBoardId);
                        JOptionPane.showMessageDialog(parent, "Ticket is successfully bought id = " + ticketDTO.getTicketId());
                        parent.dispose();
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(parent, "Connection failed: " + e.getClass() + " " + e.getMessage());
                        parent.dispose();
                    } catch (InvalidIdException e) {
                        JOptionPane.showMessageDialog(parent, "Board Id's " + departureBoardId +
                                " or " + arriveBoardId + " don't exist");
                        parent.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(parent, "Error: " + e.getMessage() );
                    }
                } else {
                    JOptionPane.showMessageDialog(parent, "Fill at least your first name! (You can leave the field Last Name empty only if you don't have it)");
                }

                parent.dispose();

            }
        });

        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parent.dispose();
            }
        });

        birthDateLabel.setText("Date of birth");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lastNameLabel)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(firstNameLabel)
                                                                .addGap(19, 19, 19)
                                                                .addComponent(firstNameField))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(69, 69, 69)
                                                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(okButton)
                                                .addGap(30, 30, 30)
                                                .addComponent(cancelButton)
                                                .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birthDateLabel))
                                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstNameLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lastNameLabel))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(okButton)
                                                        .addComponent(cancelButton))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(birthDateLabel)
                                                .addGap(2, 2, 2)
                                                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel birthDateLabel;
    private JCalendar calendar;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton okButton;
    // End of variables declaration
}