package com.tsystems.javaschool.vm.protocol;

public enum ServerResponse {
    INVALID_LOGIN_OR_PASSWORD, INVALID_START_REQUEST, INVALID_MANAGER_COMMAND,
    FAILED_CREATION, CREATION_SUCCESS, INVALID_INPUT, INVALID_ID, OPERATION_SUCCESS, FAILED_OPERATION, EXCEPTION, INVALID_SESSION
}
