package com.tsystems.javaschool.vm.client.panels.manager;

import com.tsystems.javaschool.vm.client.StartForm;
import com.tsystems.javaschool.vm.client.listeners.AddStationToPathButtonAction;
import com.tsystems.javaschool.vm.client.listeners.GetStationsOfPathButtonAction;
import com.tsystems.javaschool.vm.client.listeners.RemoveStationFromPathButtonAction;

import javax.swing.*;

public class GetStationsOfPathPanel extends JPanel {
    private StartForm parent;
    private JTabbedPane tabbedPane;
    private String pathTitle;

    /**
     * Creates new form GetStationsOfPath
     */
    public GetStationsOfPathPanel(StartForm parent, JTabbedPane tabbedPane) {
        this.parent = parent;
        this.tabbedPane = tabbedPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        label = new JLabel("Path name");
        jScrollPane1 = new JScrollPane();
        table = new JTable();
        button = new JButton("Get stations");
        textField = new JTextField();
        jLabel1 = new JLabel("Add station to path");
        stationAddField = new JTextField();
        addBeforeButton = new JButton("Add before selected");
        addEndButton = new JButton("Add to the end");
        removeButton = new JButton("Remove selected");



        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "Id", "Title", "TimeZone"
                }
        ));
        jScrollPane1.setViewportView(table);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(button, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textField, GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(stationAddField, GroupLayout.Alignment.LEADING)
                                        .addComponent(addBeforeButton, GroupLayout.Alignment.LEADING)
                                        .addComponent(addEndButton, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(removeButton, GroupLayout.PREFERRED_SIZE, 129, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 412, GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(label)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(button, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(stationAddField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addBeforeButton)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addEndButton)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(removeButton)
                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        button.addActionListener(new GetStationsOfPathButtonAction(parent, textField, this));
        addBeforeButton.addActionListener(new AddStationToPathButtonAction(parent, stationAddField, this, false));
        addEndButton.addActionListener(new AddStationToPathButtonAction(parent,  stationAddField, this, true));
        removeButton.addActionListener(new RemoveStationFromPathButtonAction(parent, this));

    }// </editor-fold>

    public void click(String pathTitle) {
        textField.setText(pathTitle);
        button.doClick();
        tabbedPane.setSelectedComponent(this);
    }

    public String getPathTitle() {
        return pathTitle;
    }

    public void setPathTitle(String pathTitle) {
        this.pathTitle = pathTitle;
    }

    public JTable getTable() {
        return table;
    }

    // Variables declaration - do not modify
    private JTable table;
    private JTextField textField;
    private JButton addBeforeButton;
    private JButton addEndButton;
    private JButton removeButton;
    private JButton button;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JLabel label;
    private JTextField stationAddField;
    // End of variables declaration
}